### ISSUE TITLE
Playing streams failed

### ISSUE THREAD

**Issue by Wooooot** [Kodehawa/MantaroBot#10]
Playing mp3 streams failed because it's continuous playing, but the bot allow only <20min

**Comment by adriantodt** [comment]
Currently supporting us on Patreon or donating unlocks the music limit, so you can play streams.

Idk if @Kodehawa thinks it's worth to doing it, anyway.

**Comment by Wooooot** [comment]
Oh well... hum... I didn't know... that it can be unlocked. 
Maybe you can do an except for streams ? I think it's the same about youtube live and all streams with non-defined duratio like radios.
Maybe a compromise is to allow to play it whatever the defined duration, but stop it like after 30min or one hour.

**Comment by Kodehawa** [comment]
https://www.patreon.com/mantaro <- Even $1 a month can unlock it, fyi

**Comment by Kodehawa** [comment]
I'll keep this open in the event we think this could be added as a normal feature

**Comment by Wooooot** [comment]
Ok ok... did you got that I'm not asking you to bypass your patreon feature ? but just allowing streams on your bot, even with a limited time ?

Just so you know :
- I'm not the owner of the channel where the bot is, and then not sure that it's up to me to support you...
- It's a bug, the bot won't play any sort of streams, whatever the duration...

I finally found a solution by using another bot... Anyway it was not the goal -_-

**Comment by Kodehawa** [comment]
The solution is to read.
Streams are longer than 21 minutes in lenght, in fact, they report a extremely large number as lenght (iirc Long.MAX_LENGHT in ms). 
A supporter gets unlimited music lenght, hence the ability to watch streams.
You donate if you like the bot, you don't if you don't. It's obviously up to you.
It's not a bug, it's intended.
