### ISSUE TITLE
Market buying noworking

### ISSUE THREAD

**Issue by aceredleo** [Kodehawa/MantaroBot#3]
Whenever I wish to buy something, I was never allowed. Even when putting the emoji.
Here's a screencap. I do have the credits to buy it.

![screenshot_10](https://cloud.githubusercontent.com/assets/26593005/24187636/e0705da4-0eab-11e7-8e76-9dbb56492c88.png)

**Comment by Kodehawa** [comment]
If the item only shows with an upwards arrow you can only sell it (it's a dropable item), if it only shows with a downwards arrow you can only buy it. Items with both arrows are sellable and buyable.
